# Generated by Django 3.2.12 on 2022-05-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0012_set_bigautofield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcasestatus",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
